### ISSUE TITLE
Compatibility with the "Nya" plugin

### ISSUE THREAD

**Issue by Yohji52** [ErisApps/SongChartVisualizer#7] opened 2021-10-18 12:37 UTC
When using the "Nya" plugin, if you select the "detach from menu" option, SongChartVisualiser would only appear until the completion of one song, by which then the chart would not appear for any songs until you restart the game, and it would only work for one song again.

**Comment by ErisApps** [comment] 2021-10-18 12:54
I cannot seem to reproduce said issue. Could you please try reproducing it again and provide your _latest.log file?

**Comment by Yohji52** [comment] 2021-10-18 13:42
It might have been one of the other two settings then, but it definitely does occur on my end with Nya as I've tested this countless of times.
[2021.10.18.21.21.26.log](https://github.com/ErisApps/SongChartVisualizer/files/7365337/2021.10.18.21.21.26.log)

**Comment by ErisApps** [comment] 2021-10-18 16:58
Issue is caused by exceptions thrown by the Nya mod, the linked PR above will fix this issue.

**Comment by ErisApps** [comment] 2021-10-18 17:56
The fix has been merged in so please grab the new version from the Nya repo (0.2.3 or higher)

**Closed as completed by ErisApps** 2021-10-18 17:56 UTC
Labels: bug
